-- Direct platform usage telemetry for Smart Console.
-- Management API credentials are encrypted with Supabase Vault and never exposed to browser clients.

create extension if not exists pg_cron;
create extension if not exists pg_net with schema extensions;

create table if not exists public.platform_usage_snapshots (
  snapshot_id bigint generated by default as identity primary key,
  captured_at timestamptz not null default now(),
  window_start timestamptz not null,
  window_end timestamptz not null,
  api_requests bigint,
  log_events bigint,
  observed_log_ingest_bytes bigint,
  log_query_scanned_bytes bigint,
  exact_egress_bytes bigint,
  exact_log_ingest_bytes bigint,
  exact_log_query_bytes bigint,
  source_breakdown jsonb not null default '{}'::jsonb,
  management_raw jsonb not null default '{}'::jsonb,
  coverage_status text not null default 'observed',
  error_message text
);

create index if not exists platform_usage_snapshots_captured_idx
  on public.platform_usage_snapshots (captured_at desc);
create index if not exists platform_usage_snapshots_window_idx
  on public.platform_usage_snapshots (window_start, window_end);

alter table public.platform_usage_snapshots enable row level security;
revoke all on public.platform_usage_snapshots from anon, authenticated;

create table if not exists public.usage_client_egress_daily (
  usage_day date not null,
  client_type text not null check (client_type in ('agent','web')),
  client_id text not null default '',
  egress_bytes bigint not null default 0 check (egress_bytes >= 0),
  reports bigint not null default 0 check (reports >= 0),
  updated_at timestamptz not null default now(),
  primary key (usage_day, client_type, client_id)
);

alter table public.usage_client_egress_daily enable row level security;
revoke all on public.usage_client_egress_daily from anon, authenticated;

create table if not exists public.usage_egress_report_ids (
  report_id uuid primary key,
  captured_at timestamptz not null default now()
);

alter table public.usage_egress_report_ids enable row level security;
revoke all on public.usage_egress_report_ids from anon, authenticated;

create or replace function public.record_client_egress(
  p_report_id uuid,
  p_client_type text,
  p_client_id text,
  p_bytes bigint
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  inserted_id uuid;
  safe_client_id text;
begin
  if p_report_id is null or p_client_type not in ('agent','web') or p_bytes < 0 or p_bytes > 52428800 then
    return false;
  end if;

  if p_client_type = 'web' then
    if auth.role() <> 'authenticated' or not exists (
      select 1 from public.console_users cu
      where lower(cu.email) = lower(coalesce((select auth.jwt())->>'email',''))
        and cu.is_active = true
    ) then
      raise exception 'Smart Console authorization required' using errcode = '42501';
    end if;
  elsif auth.role() <> 'service_role' then
    raise exception 'Agent usage reports require service role' using errcode = '42501';
  end if;

  insert into public.usage_egress_report_ids(report_id)
  values (p_report_id)
  on conflict do nothing
  returning report_id into inserted_id;

  if inserted_id is null then
    return true;
  end if;

  safe_client_id := left(coalesce(p_client_id,''), 160);
  insert into public.usage_client_egress_daily(usage_day,client_type,client_id,egress_bytes,reports,updated_at)
  values ((now() at time zone 'utc')::date,p_client_type,safe_client_id,p_bytes,1,now())
  on conflict (usage_day,client_type,client_id)
  do update set
    egress_bytes = public.usage_client_egress_daily.egress_bytes + excluded.egress_bytes,
    reports = public.usage_client_egress_daily.reports + 1,
    updated_at = now();

  return true;
end;
$$;

revoke all on function public.record_client_egress(uuid,text,text,bigint) from public, anon;
grant execute on function public.record_client_egress(uuid,text,text,bigint) to authenticated, service_role;

create or replace function public.set_supabase_management_token(p_token text)
returns void
language plpgsql
security definer
set search_path = public, vault, pg_temp
as $$
declare
  existing_id uuid;
begin
  if auth.role() <> 'service_role' then
    raise exception 'Service role required' using errcode = '42501';
  end if;
  if p_token is null or length(trim(p_token)) < 20 or length(p_token) > 500 then
    raise exception 'Invalid Management API token';
  end if;

  select id into existing_id
  from vault.secrets
  where name = 'smart_console_supabase_management_token'
  limit 1;

  if existing_id is null then
    perform vault.create_secret(
      trim(p_token),
      'smart_console_supabase_management_token',
      'Supabase Management API token used only by the Smart Console Usage Monitor'
    );
  else
    perform vault.update_secret(
      existing_id,
      trim(p_token),
      'smart_console_supabase_management_token',
      'Supabase Management API token used only by the Smart Console Usage Monitor'
    );
  end if;
end;
$$;

create or replace function public.get_supabase_management_token()
returns text
language plpgsql
security definer
set search_path = public, vault, pg_temp
as $$
declare
  token_value text;
begin
  if auth.role() <> 'service_role' then
    raise exception 'Service role required' using errcode = '42501';
  end if;
  select decrypted_secret into token_value
  from vault.decrypted_secrets
  where name = 'smart_console_supabase_management_token'
  limit 1;
  return token_value;
end;
$$;

create or replace function public.delete_supabase_management_token()
returns void
language plpgsql
security definer
set search_path = public, vault, pg_temp
as $$
begin
  if auth.role() <> 'service_role' then
    raise exception 'Service role required' using errcode = '42501';
  end if;
  delete from vault.secrets
  where name = 'smart_console_supabase_management_token';
end;
$$;

revoke all on function public.set_supabase_management_token(text) from public, anon, authenticated;
revoke all on function public.get_supabase_management_token() from public, anon, authenticated;
revoke all on function public.delete_supabase_management_token() from public, anon, authenticated;
grant execute on function public.set_supabase_management_token(text) to service_role;
grant execute on function public.get_supabase_management_token() to service_role;
grant execute on function public.delete_supabase_management_token() to service_role;

do $$
begin
  if not exists (select 1 from vault.secrets where name = 'smart_console_usage_cron_key') then
    perform vault.create_secret(
      encode(extensions.gen_random_bytes(32),'hex'),
      'smart_console_usage_cron_key',
      'Shared key for the hourly Smart Console usage collector'
    );
  end if;
  if not exists (select 1 from vault.secrets where name = 'smart_console_project_url') then
    perform vault.create_secret(
      'https://pgbipustotixwahmotvu.supabase.co',
      'smart_console_project_url',
      'CRECCOM Security Supabase project URL'
    );
  end if;
end $$;

create or replace function public.get_usage_cron_key()
returns text
language plpgsql
security definer
set search_path = public, vault, pg_temp
as $$
declare
  key_value text;
begin
  if auth.role() <> 'service_role' then
    raise exception 'Service role required' using errcode = '42501';
  end if;
  select decrypted_secret into key_value
  from vault.decrypted_secrets
  where name = 'smart_console_usage_cron_key'
  limit 1;
  return key_value;
end;
$$;
revoke all on function public.get_usage_cron_key() from public, anon, authenticated;
grant execute on function public.get_usage_cron_key() to service_role;

create or replace function public.get_direct_usage_summary()
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  caller_email text := lower(coalesce((select auth.jwt())->>'email',''));
  cycle_start timestamptz := date_trunc('month', now());
  latest public.platform_usage_snapshots%rowtype;
  observed_ingest bigint := 0;
  estimated_query bigint := 0;
  direct_egress bigint := 0;
  client_egress bigint := 0;
  api_requests bigint := 0;
  log_events bigint := 0;
begin
  if auth.role() <> 'authenticated' or caller_email = '' or not exists (
    select 1 from public.console_users cu
    where lower(cu.email) = caller_email and cu.is_active = true
  ) then
    raise exception 'Smart Console authorization required' using errcode = '42501';
  end if;

  select * into latest
  from public.platform_usage_snapshots
  order by captured_at desc
  limit 1;

  select
    coalesce(sum(s.observed_log_ingest_bytes),0),
    coalesce(sum(s.log_query_scanned_bytes),0),
    coalesce(max(s.exact_egress_bytes),0),
    coalesce(sum(s.api_requests),0),
    coalesce(sum(s.log_events),0)
  into observed_ingest, estimated_query, direct_egress, api_requests, log_events
  from public.platform_usage_snapshots s
  where s.window_end >= cycle_start;

  select coalesce(sum(egress_bytes),0)
  into client_egress
  from public.usage_client_egress_daily
  where usage_day >= (cycle_start at time zone 'utc')::date;

  return jsonb_build_object(
    'connected', exists (
      select 1 from vault.decrypted_secrets
      where name = 'smart_console_supabase_management_token'
        and decrypted_secret is not null
    ),
    'lastCapturedAt', latest.captured_at,
    'windowStart', latest.window_start,
    'windowEnd', latest.window_end,
    'coverageStatus', latest.coverage_status,
    'error', latest.error_message,
    'apiRequestsThisCycle', api_requests,
    'logEventsThisCycle', log_events,
    'observedLogIngestBytesThisCycle', observed_ingest,
    'trackedLogQueryBytesThisCycle', estimated_query,
    'exactEgressBytesThisCycle', nullif(direct_egress,0),
    'measuredSmartConsoleEgressBytesThisCycle', client_egress,
    'sourceBreakdown', coalesce(latest.source_breakdown,'{}'::jsonb),
    'managementAvailable', latest.snapshot_id is not null,
    'note', 'Unified billing egress/log meters are used when Supabase exposes them through supported APIs. Otherwise the monitor shows direct API/log observations and measured Smart Console payload egress.'
  );
end;
$$;

revoke all on function public.get_direct_usage_summary() from public, anon;
grant execute on function public.get_direct_usage_summary() to authenticated;

-- Keep duplicate-report memory small.
select cron.unschedule(jobid)
from cron.job
where jobname = 'smart-console-usage-report-id-cleanup';
select cron.schedule(
  'smart-console-usage-report-id-cleanup',
  '25 2 * * *',
  $$delete from public.usage_egress_report_ids where captured_at < now() - interval '3 days';$$
);

-- Invoke the usage collector hourly. It safely no-ops until a Management API token is connected.
select cron.unschedule(jobid)
from cron.job
where jobname = 'smart-console-direct-usage-collector';
select cron.schedule(
  'smart-console-direct-usage-collector',
  '17 * * * *',
  $$
  select net.http_post(
    url := (select decrypted_secret from vault.decrypted_secrets where name = 'smart_console_project_url')
      || '/functions/v1/usage-platform-monitor',
    headers := jsonb_build_object(
      'Content-Type','application/json',
      'x-usage-cron-key',(select decrypted_secret from vault.decrypted_secrets where name = 'smart_console_usage_cron_key')
    ),
    body := jsonb_build_object('action','collect','scheduledAt',now()),
    timeout_milliseconds := 30000
  );
  $$
);
